[package]
name = "fastq_count"
version = "0.8.0"
authors = ["d2jvkpn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_cmd = "1"

[dependencies]
clap = "2"
flate2 = "1.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4"
